[colors]
[colors.primary]
background = "#4A4A4A"
foreground = "#8E8E8E"
dim_foreground = "#ffffff"

[colors.cursor]
text = "#ffffff"
cursor = "#848484"

[colors.selection]
text = "CellForeground"
background = "#6F6F6F"

[colors.normal]
black   = "#3B3B3B"  
red     = "#5C5C5C"  
green   = "#6A6A6A"  
yellow  = "#7A7A7A"  
blue    = "#9D9D9D"  
magenta = "#B6B6B6"  
cyan    = "#CECECE"  
white   = "#E5E5E5"  

[colors.bright]
black   = "#5A5A5A"  
red     = "#707070"  
green   = "#8D8D8D"  
yellow  = "#A5A5A5"  
blue    = "#B8B8B8"  
magenta = "#CECECE"  
cyan    = "#E0E0E0"  
white   = "#F0F0F0"  

[colors.dim]
black   = "#444444"  
red     = "#505050"  
green   = "#5E5E5E"  
yellow  = "#6C6C6C"  
blue    = "#7A7A7A"  
magenta = "#8A8A8A"  
cyan    = "#9D9D9D"  
white   = "#B8B8B8"  

